
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseTerraform@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/path-to-your-terraform-files'
  displayName: 'Terraform Init'

- task: UseTerraform@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/path-to-your-terraform-files'
    additionalArgs: '-auto-approve'
  displayName: 'Terraform Apply'
